# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='quote',
        ),
    ]
