# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180802_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added_by',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
