# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_quote_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default='uknown2', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='blog.User'),
        ),
    ]
