# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180803_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='added_by',
        ),
    ]
